name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test

  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run UI Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          disable-animations: true   # 👈 ADD THIS
          script: ./gradlew connectedAndroidTest